#!/usr/bin/env python3
# Turns compiled SPIR-V modules into a C header of uint32_t arrays, so the shaders are embedded in
# the binary and no files have to be found or shipped alongside it.
#
# Usage: spv2c.py <output.h> <SymbolName>=<input.spv> [<SymbolName>=<input.spv> ...]

import sys, os


def main(argv):
    if len(argv) < 3:
        print("usage: spv2c.py <output.h> <Symbol>=<input.spv> ...", file=sys.stderr)
        return 2

    out_path = argv[1]
    entries = []

    for arg in argv[2:]:
        if "=" not in arg:
            print("expected Symbol=path, got %s" % arg, file=sys.stderr)
            return 2
        symbol, path = arg.split("=", 1)
        with open(path, "rb") as f:
            data = f.read()
        if len(data) % 4 != 0 or len(data) < 20:
            print("%s is not a plausible SPIR-V module" % path, file=sys.stderr)
            return 1
        # SPIR-V magic, little endian. Catches a truncated or wrong-endian build early rather than
        # as an opaque vkCreateShaderModule failure at runtime.
        if data[0:4] != b"\x03\x02\x23\x07":
            print("%s does not start with the SPIR-V magic number" % path, file=sys.stderr)
            return 1
        words = [int.from_bytes(data[i:i + 4], "little") for i in range(0, len(data), 4)]
        entries.append((symbol, words))

    guard = "BS_" + os.path.basename(out_path).replace(".", "_").upper()
    lines = [
        "/* Generated by tools/spv2c.py. Do not edit. */",
        "#ifndef %s" % guard,
        "#define %s" % guard,
        "",
        "#include <stdint.h>",
        "",
    ]

    for symbol, words in entries:
        lines.append("static const uint32_t %s[] = {" % symbol)
        for i in range(0, len(words), 8):
            lines.append("    " + " ".join("0x%08x," % w for w in words[i:i + 8]))
        lines.append("};")
        lines.append("")

    lines.append("#endif")

    with open(out_path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")

    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
